#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart

# killall if already
killall -9 picom xfce4-power-manager sxhkd fcitx5 

# start hotkey
sxhkd &

# Start polybar
sh ~/.config/polybar/launch.sh --blocks &

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# picom
picom --experimental-backends --config ~/.config/bspwm/picom.conf &

# Low battery notifier
sh ~/.config/bspwm/scripts/low_bat_notifier.sh &

# powermanager
xfce4-power-manager &

# key
fcitx5 &

# double border
# sh ~/.config/bspwm/scripts/border.sh
